#!/usr/bin/env python3

import sys
from transformers.utils import logging
import csv
import pandas as pd

DATA_PATH = "../../HW01/documents"

if __name__ == "__main__":
    context_file_name = sys.argv[1]
    logging.set_verbosity_error()
    logging.disable_progress_bar()
    
    related_sentences = []
    answers = []

    try:
        questions_output = pd.read_csv("../data/medium-hard-questions.csv")
    except FileNotFoundError:
        questions_output = pd.DataFrame(columns=['document_id', 'question', 'answer', 'difficulty'])
    
    questions_df = pd.read_csv("../data/qa_dataset-0.1.csv")
    
    questions_df['difficulty'] = questions_df['difficulty'].str.strip()
    questions_df = questions_df.drop(columns=['Unnamed: 0'])

    relevant_df = questions_df[
        (questions_df['document_id'] == context_file_name)
        & (questions_df['difficulty'] != 'E')
    ]

    questions_output.reset_index(drop=True, inplace=True)
    relevant_df.reset_index(drop=True, inplace=True)

    print(relevant_df)

    questions_output = pd.concat(
        [
            questions_output,
            relevant_df
        ]
    )

    questions_output.to_csv("../data/medium-hard-questions.csv", index=False)
