#!/usr/bin/env python3

import sys
from transformers.utils import logging
import csv

DATA_PATH = "../../HW01/documents"

if __name__ == "__main__":
    context_file_name = sys.argv[1]
    logging.set_verbosity_error()
    logging.disable_progress_bar()
    
    related_sentences = []
    answers = []
    
    with open("medium-hard-questions.csv", "a") as questions_file:
        writer = csv.writer(questions_file)
        with open("../data/qa_dataset-0.1.csv") as questions_data:
            questions = questions_data.readlines()
            for question in questions[1:]:
                q_cols = question.split(",")
                print(q_cols)
                if (
                    q_cols[1] == context_file_name
                    and q_cols[4].strip() in ["M", "H"]
                ):
                    writer.writerow([
                        question,
                    ])
                
            

    
    
